// <auto-generated />
using Bunnymail.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bunnymail.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20230419213659_Bunnymail_M1")]
    partial class Bunnymail_M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("Bunnymail.Entities.EventTemplate", b =>
                {
                    b.Property<string>("Event")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Event");

                    b.ToTable("EventTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
