apiVersion: v1
kind: PersistentVolume
metadata:
  name: bunnymail-pv
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bunnymail-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunnymail
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunnymail
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bunnymail
    spec:
      containers:
      - name: bunnymail
        image: bunnymail:6.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: configfile
          value: '/usr/db/bunnymailconfig.json'
        - name: rabbithost
          value: rabbitmq.rabbit
        - name: rabbituser
          value: '###'
        - name: rabbitpass
          value: '###'
        - name: sendgridapikey
          value: 'abcdefg12345678'
        - name: swagger
          value: ''
        - name: logmessages
          value: 'yes'
        - name: username
          value: demo@contoso.com
        - name: password
          value: password
        volumeMounts:
        - name: confpath
          mountPath: /usr/db
      volumes:
      - name: confpath
        persistentVolumeClaim:
          claimName: bunnymail-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bunnymail-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: bunnymail
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
